config/routes.rb
Rails.application.routes.draw do

# USERS
  resources :users
  get "users/:id/posts", to: "users#posts"
  get "/", to: "users#index", as: "homepage"
  get "/users/:id", to: "users#show"

# POSTS
  resources :posts

# SESSIONS
  get "/signin", to: "sessions#new", as: "signin"
  post "/sessions", to: "sessions#create"
  delete "/logout", to:"sessions#delete"

# CITIES
  resources :cities do
    resources :posts
  end
  get "cities/:id/posts", to: "cities#posts"


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Post, user_id: user.id
    can :manage, User, user_id: user.id
  end
end

app/models/city.rb
class City < ActiveRecord::Base

  has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  belongs_to :city

  validates :title, presence: true, length: { maximum: 200 }
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts
  has_secure_password

  has_attached_file :avatar, styles: { large: "400x400>", medium: "300x300>", thumb: "100x100>" }, default_url: "Ben.jpeg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /@/}

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  include SessionsHelper

  rescue_from CanCan::AccessDenied do |exception|
     redirect_to root_url, :alert => exception.message
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @city = City.all
    render :index
  end

  def show

    @post = Post.find(params[:id])
    @user = User.find(params[:id])
    @city = City.find(params[:id])
    @posts = City.find(params[:id]).posts
    @confirm_msg = "Are you sure you want to delete #{@post.title} ?"
    render :show
  end

  def posts
    @posts = City.find(params[:id]).posts
    @city = City.find(params[:id])
  end


  #   def create
  #   @post = .posts.build(cities_params)
  #   if @post.create
  #     redirect_to city_posts_path
  #   else
  #     redirect_to new_city_post_path
  #   end
  # end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @city = City.find_by_id(params[:city_id])
    render :index
  end

  def new
    @post = Post.new
    @city = City.find_by_id(params[:city_id])
    render :new
  end

  def create

    post_params = params[:post]
    post = Post.new({title: post_params[:title], description: post_params[:description]})
    # @post = current_user.posts.build(params[:city_id])
    if post.save
    city = City.find(params[:city_id])
    city.posts << post
    current_user.posts << post
      if city.save && current_user.save
        flash[:notice] = "Post created!"

      redirect_to city_path(city.id)
      else
        flash[:error] = post.errors.full_messages.join("-----")
       redirect_to new_city_post_path
      end
    else
      flash[:error] = post.errors.full_messages.join("-----")
      redirect_to new_city_post_path
    end

  end


  def show
    @post = Post.find(params[:id])
    @city = @post.city_id
    @first_name = @post.user.first_name
    @confirm_msg = "Are you sure you want to delete #{@post.title} ?"
    render :show
  end



  def edit
    @post = Post.find(params[:id])
    authorize! :manage, @post
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    authorize! :manage, @post
    @post.update(post_params)
    redirect_to "/posts/#{@post.id}"
  end



  def destroy
    @post = Post.find(params[:id])
    authorize! :manage, @post
    city = City.find(params[:city_id])
    @post.destroy
    flash[:notice] = "'#{@post.title}' post was deleted"
    redirect_to city_path(city.id)
  end


  private

  def post_params
    params.require(:post).permit(:title, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      flash[:notice] = "Welcome back #{@user.first_name}"
      login(@user)
      redirect_to "/users/#{@user.id}"
    else
      flash[:error] = "The e-mail or password you entered is incorrect. Please try again"
      redirect_to signin_path
    end
  end

  def delete
    logout
    redirect_to homepage_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Hello, #{@user.first_name}! Welcome to Vagabond!"
      login(@user)
      redirect_to "/users/#{@user.id}"
    else
      flash[:error] = @user.errors.full_messages.join("-----")
      redirect_to new_user_path
    end

  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    render :show
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if current_user == @user
      @user.update_attributes(user_params)
      if @user.save
        flash[:notice] = "Profile Updated!"
        redirect_to "/users/#{@user.id}"
      else
        flash[:error] = @user.errors.full_messages.join("---")
        redirect_to "/users/#{@user.id}/edit"
      end
    else
      flash[:notice] = "Bad Hacker!"
      redirect_to "/"
    end
  end


  def posts
    @posts = User.find(params[:id]).posts
  end

  private

  def user_params


    params.require(:user).permit(:first_name, :last_name, :email, :location, :password, :avatar)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to "/sign_in"
    end
  end

  def logout
    session.delete(:user_id)
    @current_user = session[:user_id] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
Hello World! Cities Go Here. </br>

<% @city.each do |city| %>
  <a href="/cities/<%= city.id %>">
    <%= city.name %> </br>
  </a>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/cities/new.html.erb
<div class="container">
  <%= form_for @cities do |f| %>

  <div>
   <%= f.file_field :avatar %>
  </div>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.text_field :description, placeholder: "Description" %>
  </div>

  <br>
    <%= f.submit "Create Post" %>
  <br>

  <% end %>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/cities/show.html.erb
<div class="container">
  <div class="card-panel">

    <div class="row">
      <div class="col l6">
        <h2><%= @city.name %></h2>
        <button class="btn waves-effect waves-light indigo accent-3">
          <%= link_to "Create Post", new_city_post_path(@city[:id]), {style: "color: white"} %>
          <i class="material-icons right">send</i>
        </button>


        <h5>Country: </h5><%= @city.country %>
      </div>
      <div class="col l6">
        <img class="responsive-img" src="/<%= @city.id %>.jpg">
      </div>
    </div>

        <h5>Description: </h5> <%= @city.description %></br>
        </br>


        <h5>Posts: </h5>
        <% @posts.each do |post| %>
        <div class="card-panel">
          <div class="green">
            <h4><i class="tiny material-icons white-text">message</i><a href="/cities/<%= @city.id %>/posts/<%= post.id %>" class="button-link">  <%= post.title %></h4></a>
            <i class="tiny material-icons white-text">perm_identity</i><strong><a href="/users/<%= post.user_id %>" class="button-link">  <%= post.user.first_name %> <%= post.user.last_name %></a></strong></br>
          </div>
          <%= truncate(post.description, :length => 1000) %></br><a href="/cities/<%= @city.id %>/posts/<%= post.id %>" class="text-link">See more...</a>
        </div>

        <% end %>

  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagabond App</title>
    <!-- CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <!-- JAVASCRIPTS -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.2.3.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

  </head>

  <body class="grey lighten-2">
    <nav class="grey darken-4">
      <div class="navbar-wrapper container">
        <a href="/" class ="brand-logo class green-text"><strong>VAGABOND</strong></a>

        <ul class="right">
        <% if session[:user_id].nil? %>

          <li><%= link_to "User Login", signin_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>

        <% else %>

          <li><%= link_to "Profile", user_path(current_user[:id]) %></li>
          <li><%= link_to "Log Out", logout_path, method: "delete" %></li>

        <% end %>
      </ul>

      </div>
    </nav>

    <div class="container">
      <div class="row cities">
        <div class="col s12">
          <ul class="collapsible" data-collapsible="accordion">
            <li>
              <div class="collapsible-header"><i class="material-icons indigo-text text-accent-3">location_on</i>Cities
              </div>
              <div class="collapsible-body center-align" id="cities">
                <a class="btn indigo accent-3 white-text cities" href="/cities/1">San Francisco</a>
                <a class="btn indigo accent-3 white-text cities" href="/cities/2">London</a>
                <a class="btn indigo accent-3 white-text cities" href="/cities/3">Gibraltar</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <% flash.each do |name, msg| %>
      <div class="errormsg">
        <%= msg %>
      </div>
      <% end %>
    </div>

  <%= yield %>

  </body>

</html>

app/views/posts/edit.html.erb
<div class="card-panel">
<%= form_for @post do |f| %>
  <h4 class="card-panel green lighten-1 white-text">Edit Post</h4>
  <div>
    <h5>Title:</h5>
    <%= f.text_field :title %>
  </div>
  <div>
    <h5>Description:</h5>
    <%= f.text_field :description %>
  </div>

  <br>
  <%= f.submit "Update Post" %>
</div>
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/posts/index.html.erb
<div class="container">
  <div class="card-panel">
    <h4 class="card-panel green lighten-1 white-text">Recent Posts</h4>

    <ul>
      <li>
        <% @posts.each do |post| %>
          <%= link_to(post.title, city_post_path(@city.id, post.id)) %><br>
        <% end %>
      </li>
    </ul>
  </div>
</div>  

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/posts/new.html.erb
<div class="container">
  <div class="card-panel">
    <%= form_for @post, url: "/cities/#{@city.id}/posts" do |f| %>

    <h2><%= @city.name %></h2>
    <div>
      <h5>Add a Photo:</h5>
      <%= f.file_field :avatar %>
    </div>
    <div>
      <%= f.text_field :title, placeholder: "Title" %>
    </div>
    <div>
      <%= f.text_field :description, placeholder: "Description" %>
    </div>

    <br>
      <%= f.submit "Create Post", :class => "button" %>
    <br>

    <% end %>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/posts/show.html.erb
<div class="container">
  <div class="card-panel">
    <div class="header card-panel green lighten-1 content white-text">
      <h4><%= @post.title %></h4>
      <p>
        <i class="tiny material-icons">perm_identity</i><strong><a class="blue-text text-darken-3" href="/users/<%= @post.user_id %>"> <%= @post.user.first_name %> <%= @post.user.last_name %></a><br>

        <i class="material-icons">location_on</i><a class="blue-text text-darken-3" href="/cities/<%= @post.city_id %>"> <%= @post.city.name %> </a></br>
        <%= @post.created_at.strftime("%b %d, %Y") %></strong>
      </p>
    </div>
    <p class="flow-text white black-text">
      <%= @post.description %>
    </p>

  <% if can? :manage, @post %>

    <div>
      <form action='/posts/<%= @post.id %>/edit' method='get'>
        <button> Edit Post </button>
      </form>
    </div>

    <%= button_to "Delete Post", city_post_path(@post.city.id, @post.id), method: :delete, :data => {:confirm => @confirm_msg} %>

  </div>

  <% end %>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/users/edit.html.erb
<div class="container">
  <%= form_for @user do |f| %>

  <div>
   <%= f.file_field :avatar %>
  </div>
  <div>
  <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
  <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
  <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.text_field :location, placeholder: "Location" %>
  </div>
  <br>
  <%= f.submit "Update Profile" %>

  <% end %>

</div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/users/index.html.erb
 <div class="slider">
            <ul class="slides">
                <li>
                  <a href="cities/1">
                    <img src="/sanfrancisco.gif">
                    <div class="caption bottom-align">
                        <h1>San Francisco</h1>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="cities/2">
                    <img src="/london.gif">
                    <div class="caption left-align">
                        <h1>London</h1>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="cities/3">
                    <img src="/gibraltar.gif">
                    <div class="caption left-align">
                        <h1>Gibraltar</h1>
                    </div>
                  </a>
                </li>
            </ul>
        </div>
        <!--your code end-->


<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/users/new.html.erb
<div class="container">
  <div class="card-panel">
    <%= form_for @user do |f| %>

    <div>
      <h5>Add a Photo:</h5>
     <%= f.file_field :avatar %>
    </div>
    <div>

    <%= f.text_field :first_name, placeholder: "First Name" %>
    </div>
    <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
    </div>
    <div>
    <%= f.text_field :email, placeholder: "Email" %>
    </div>
    <div>
      <%= f.text_field :location, placeholder: "Location" %>
    </div>
    <div>
      <%= f.password_field :password, placeholder: "Password" %>
    </div>


    <br>
      <%= f.submit "Sign up", :class => "button" %>
    <br>

    <% end %>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/users/posts.html.erb
<% @posts.each do |post| %>
<div>
  <%= link_to(post.title, city_post_path(post.city_id, post.id)) %>

</div>
<div>
  <%= post.description %>
</div>
<br>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

app/views/users/show.html.erb
<div class="container">
  <div class="card-panel">


  <div class="row">
    <div class="col l4">
      <h4><%= @user.first_name %>'s Profile</h4>
      <div class="responsive-img">
        <%= image_tag(@user.avatar, :class => "profile-pic")%></img>
      </div>
      <div>
        <strong>Name: </strong><%= @user.first_name %> <%= @user.last_name %>
      </div>
      <div>
        <strong>Email: </strong> <%= @user.email %>
      </div>
      <div>
        <strong>Location: </strong> <%= @user.location %>
      </div>
      <div>
        <strong>User Since: </strong> <%= @user.created_at.strftime("%b %d, %Y") %>
      </div>
      <br>

    </div>

    <div class="col l8">
      <br>
      <% if current_user.id == @user.id %>
      <div class="button white-text right">
        <a href='/users/<%= @user.id %>/edit' class="button-link">Edit Profile</a>
      </div>
      <% end %><br>
      <br>
     <h5>Recent Posts:</h5>
     <div class="card-panel">
        <% @posts.each do |post| %>
      </br><div class="postcontainer">
        <div class="titlelabel">
          <strong><a href="/cities/<%= post.city_id %>/posts/<%= post.id %>"><%= post.title %></a></strong></div>
          <strong>Posted in: </strong><a href="/cities/<%= post.city_id %>"> <%= post.city.name %></a></br></br>
          <%= truncate(post.description, :length => 1000) %> <a href="/cities/<%= post.city_id %>/posts/<%= post.id %>">See More...</a></br></br>
          <div class="postingdate">
            <label>Posted on: </label><%= post.created_at.strftime("%b %d, %Y") %></br>
          </div>
        </div>
        <% end %>
      </div>
    </div>

  </div>

</div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>